### GENERAL VARIABLES ###
PAIRED_END: ""

### INPUT FILES ###

# Complete these two fields if the sequencing is in Paired_End AND the raw fastq files are multiplexed, if not leave blank: ""
# File extension format: _R1.fastq.gz and _R2.fastq.gz
FASTQ_R1: ""
FASTQ_R2: ""

# Complete this field if the raw fastq files are demultiplexed (sequencing Single_end or paired_end), if not leave blank: ""
# File extension format: PairedEnd > sampleX.R1.fastq.gz and sampleX.R2.fastq.gz / SingleEnd > sampleX.fastq.gz
DEMULT_DIR: ""

# Mandatory files:
# Complete this field if the raw fastq files are multiplexed (sequencing Single_end or paired_end), if not leave blank: ""
BARCODE_FILE: ""
# Complete this field in all cases
ADAPTER_FILE: ""


### DEMULTIPLEXING PARAMETERS ###

# Complete these two fields if the raw fastq files is multiplexed, if not leave blank: ""
DEMULT_SUBSTITUTIONS: ""
CUTADAPT_DEMULT_EXTRA_OPTIONS: ""

### UMI EXTRACTION PARAMETERS ###
UMI: ""
UMITOOLS_EXTRACT_OPTIONS: ""

### TRIMMING PARAMETERS ###
TRIMMING_QUAL: ""
TRIMMING_MIN_LENGTH: ""
CUTADAPT_TRIMMING_EXTRA_OPTIONS: ""
